### ISSUE TITLE
Don't use redirects for error messages

### ISSUE THREAD

**Issue by npmccallum** [profianinc/benefice#103]
https://github.com/profianinc/benefice/commit/d8107419769f7cd9f08d366332f888ec58bce839

I disagree with the approach in the above commit. The `POST` should return `TOO_MANY_REQUESTS` and the `Deploy` action should be AJAXified. When the AJAX call detects `TOO_MANY_REQUESTS` it should update the error with Javascript.

**Comment by npmccallum** [comment]
@bstrie Could I get a quick review of this so that @rvolosatovs can merge in the morning? Thanks!

**Comment by definitelynobody** [comment]
I agree. We should also probably use something like react or seed to manage the frontend scripting so the error handling can live completely on the client.
