### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by definitelynobody** [profianinc/benefice#118]
In order to simplify the user experience we should:

Break the main page into separate pages
- [x] `/` A page for launching examples trivially
  - Link to source
  - Ports handled automatically
- [x] `/drawbridge` A page for deploying custom drawbridge slugs
  - Port mapper, which may be autopopulated by Enarx.toml if possible
- [x] `/upload` A page for deploying Wasm+configs directly
  - Direct WebAssembly file upload
  - Config editor

1) No pages should have optionally components (this simplifies scripting and is less jarring for the user)
2) All pages should use as few ui elements and clicks as possible
3) Each page should include workload limits where relevant (drawbridge has no size limit)
4) No existing functionality should be inaccessible (except editing Enarx.toml from drawbridge)
5) Deployments happen on the current page
6) If the user is not logged in, they should see the entire form but it's all greyed out/disabled
7) Authenticated users should get redirected from / to /demo

**Comment by nickvidal** [comment]
Thanks @definitelynobody, looks good to me!

**Comment by definitelynobody** [comment]
progress so far:

"/" basic page
![image](https://user-images.githubusercontent.com/51100439/183687979-3922d7a8-05ac-44dd-9d97-3707c51fb394.png)


"/advanced" page
![image](https://user-images.githubusercontent.com/51100439/183688293-6bd7fc87-6664-4cef-9560-cb0e1a6f63e7.png)
