### ISSUE TITLE
Create some built in examples

### ISSUE THREAD

**Issue by definitelynobody** [profianinc/benefice#12]
It would be nice if there were some simple built in example files which users could select to run. This would help people understand some of the `Enarx.toml` syntax and whats possible. There should also be link(s) to the sources of the examples.

**Comment by npmccallum** [comment]
The examples should be stored in drawbridge.

**Comment by rvolosatovs** [comment]
> The examples should be stored in drawbridge.

What we've discussed here during the call today is that we should probably have a repository of examples per-language (cc @bstrie). E.g. the Cryptle demo implemented in different languages.
We could then build these examples and store them in Drawbridge.

**Comment by definitelynobody** [comment]
blocked by #27

**Comment by MikeCamel** [comment]
Although I like examples per language, more important it a few really interesting examples: an AI/ML workload, a signing server, HTTPS echo server, ...
