### ISSUE TITLE
Cryptle inaccessible in production

### ISSUE THREAD

**Issue by definitelynobody** [profianinc/benefice#162]
In staging the user will be able to skip the security warning

![image](https://user-images.githubusercontent.com/51100439/187715236-45e39307-02c6-49c7-9346-d50821822a0c.png)

Which we can warn the user about in the example description. However in production HSTS prevents accessing it completely:

![image](https://user-images.githubusercontent.com/51100439/187715483-a0cae227-8e76-47c6-a9fb-5d3ff0f3f59a.png)

**Comment by npmccallum** [comment]
This issue is high priority.

**Comment by rvolosatovs** [comment]
Cryptle is the first example I always test on Benefice and I cannot reproduce this on SGX
![2022-08-31-19:58:58-screenshot](https://user-images.githubusercontent.com/12877905/187747466-9c79c0eb-5e75-421e-ac9d-e964518a4af1.png)

**Comment by rvolosatovs** [comment]
![2022-08-31-20:00:18-screenshot](https://user-images.githubusercontent.com/12877905/187747608-53f97b1f-68e5-42b7-abe5-24b87036e31e.png)
Same with SNP

**Comment by rvolosatovs** [comment]
I can reproduce this on my phone though.
https://github.com/profianinc/infrastructure/issues/69 was supposed to fix this

**Comment by platten** [comment]
@definitelynobody pending code change.

**Comment by puiterwijk** [comment]
As soon as a release is made, this can be fixed.

**Comment by rvolosatovs** [comment]
@puiterwijk can this be closed now?

**Comment by definitelynobody** [comment]
I can access it in production. Closing in favor of https://github.com/profianinc/benefice/issues/185
