### ISSUE TITLE
Collision-Resistant Listening Sockets

### ISSUE THREAD

**Issue by npmccallum** [profianinc/benefice#20]
Currently, all workloads are deployed in the same network namespace. This means that listening sockets are likely to collide, [even if chosen randomly](https://en.wikipedia.org/wiki/Birthday_problem). We should come up with some way to make this more reasonable.

One such proposal is to allocate a block of public IP addresses to the server and start each workload in a separate network namespace with an ipvlan interface.

**Comment by definitelynobody** [comment]
Workloads run in docker as of #123

**Comment by rvolosatovs** [comment]
Closing, since this is now done
