### ISSUE TITLE
Incorrect port is used in generated URLs

### ISSUE THREAD

**Issue by puiterwijk** [profianinc/benefice#252]
The URLs that get generated to the workload, use the in-docker port, instead of the port they are mapped to on the host network.
So after starting the workload, I see under Ports: `Port 63952 -> 10030 ([link](https://sgx.azure.try.profian.cloud:10030/))`: note the link points to port 10030, which doesn't work. Changing the port to 63952 does work.

**Comment by dpal** [comment]
Addressed
