### ISSUE TITLE
Different workload scheduling for stargazers

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/benefice#3]
Only users that have starred the project should be able to add items to the workload queue

After #6 is done, on scheduling request:
1. Use the OIDC subject received from the UserInfo request to get the Auth0 user https://auth0.com/docs/api/management/v2/#!/Users/get_users_by_id
2. For each object contained in `identities` field with `provider` field value equal to `github`, collect the `access_token` field into a vector. Something like
```rust
let github_tokens: Vec<_> = info.identities.into_iter().filter_map(|id| if id.provider == "github" { Some(id.access_token) } else { None }).collect())
```
3. If the `github_tokens` vector is empty after previous step, return an error stating that the user should login with github
4. For each token in `github_tokens`, check that the user has starred https://github.com/enarx/enarx repository https://docs.github.com/en/rest/activity/starring#check-if-a-repository-is-starred-by-the-authenticated-user 
```
curl -v -H "Authorization: Bearer gho_<TOKEN>" https://api.github.com/user/starred/enarx/enarx
```
Once a successful code is received, abort the search and authorize scheduling, otherwise return an error stating that the user should star the `enarx/enarx` repository and provide a URL to it in the error message

**Comment by MikeCamel** [comment]
> Yes, most important change is that we will allow all users to execute workloads. Question is with what limitations. @npmccallum what benefits will stargazers receive? Some ideas:
> 
>     * double the execution time (15s -> 30s), trivial to implement
>

We're going to want to make this a few minutes, I think, to allow more realistic testing.

>     * allow networking/attestation for stargazers. May be a bit too restrictive and potentially difficult to implement
> 
>     * allow running only preset examples for non-stargazers and enable custom workload/config combos for stargazers.

**Comment by npmccallum** [comment]
@rvolosatovs Let's start with just runtime. 5min for non-stargazers. 30 min for stargazers. @MikeCamel does that sound good?
