### ISSUE TITLE
Improve deploy button

### ISSUE THREAD

**Issue by npmccallum** [profianinc/benefice#57]
The deploy button has the following problems:

- [ ] It is verbose
- [ ] It is inconsistently capitalized
- [ ] It is underneath the wasm uploader widget

I suspect the page would look better if the deploy button was right-aligned. For example:

```
[wasmfile] <---- space ----> [deploy]
```

**Comment by definitelynobody** [comment]
I believe this is addressed in https://github.com/profianinc/benefice/pull/54
