### ISSUE TITLE
Workload deployment fails with no output and eventual 504 timeout

### ISSUE THREAD

**Issue by rvolosatovs** [profianinc/benefice#82]
Release https://github.com/profianinc/benefice/releases/tag/v0.1.0-rc10 fails to deploy workloads, instead the window starts loading forever rendering server unusable until restart. Eventually Nginx fails with 504 (gateway timeout) if you wait long enough

https://user-images.githubusercontent.com/12877905/180764023-40a42a18-f8b4-4abe-8b66-29818294feeb.mp4

**Comment by definitelynobody** [comment]
replicated this locally

**Comment by rvolosatovs** [comment]
@definitelynobody is this fixed now?

**Comment by rvolosatovs** [comment]
@definitelynobody @npmccallum is this fixed now?

**Comment by npmccallum** [comment]
I don't see it in my code.

**Comment by rvolosatovs** [comment]
Looks like it's fixed in v0.1.0-rc11
