### ISSUE TITLE
Support linking to workloads

### ISSUE THREAD

**Issue by nickvidal** [profianinc/benefice#93]
Adding this proposal as a starting point for a discussion around the UI to load workloads from GitHub/Drawbridge.

On the running page (and on the upload page), have a Wasm gallery like:

![wasm_gallery](https://user-images.githubusercontent.com/7810941/181033699-c377e3ca-d806-4b5e-bf12-e9b93ea8544b.png)

Selecting a demo will populate the 'Load URL' field on the upload page:

![load_url](https://user-images.githubusercontent.com/7810941/181035026-3ee5b5db-fde8-47e3-a931-7a262d8b7079.png)

**Comment by definitelynobody** [comment]
FYI a lot of work has been done in #68 for this. I think a good follow up issue for this would be adding a `/drawbridge/{slug}` that we can link to which will find the latest tag and select it. That way anyone can easily link their slugs to their friends or we can use it internally for linking examples
